name: build
on: push

jobs:
  build-test:
    runs-on: "windows-latest"
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v7

    - uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64
        path-type: inherit
    - uses: ZhongRuoyu/setup-llvm@v0
    - uses: actions/setup-python@v7
      with:
        python-version: "3.13"
    - run: python -m pip install build meson meson-python ninja vapoursynth

    - run: CC=clang CXX=clang++ CFLAGS="-march=x86-64-v3 -mtune=znver2" CXXFLAGS="-march=x86-64-v3 -mtune=znver2" LDFLAGS="-fuse-ld=lld" python -m build --no-isolation
    - run: wheel tags --python-tag py3 --abi-tag none dist/*.whl

    - uses: actions/upload-artifact@v7
      with:
        path: ./dist/*.whl
