name: build
on: push

jobs:
  build-test:
    runs-on: "windows-latest"
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v7

    - uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64
        path-type: inherit
        install: >-
          mingw-w64-clang-x86_64-meson
          mingw-w64-clang-x86_64-ninja
    - uses: ZhongRuoyu/setup-llvm@v0
    - uses: actions/setup-python@v7
      with:
        python-version: "3.13"
    - run: which python
    - run: echo $pythonLocation
    - run: python -m pip install cibuildwheel

    - run: python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v7
      with:
        path: ./wheelhouse/*.whl
