name: build
on:
  push:
  release:
    types:
    - published

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            shell: msys2 {0}
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          - os: macos-26-intel
            shell: bash
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
    - uses: actions/checkout@v7

    - uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64
        path-type: inherit
      if: ${{ runner.os == 'Windows' }}
    - uses: ZhongRuoyu/setup-llvm@v0
      if: ${{ (runner.os == 'Windows' && runner.arch == 'X64') || runner.os == 'Linux' }}
    - uses: ConorMacBride/install-package@v1
      with:
        brew: llvm lld
      if: ${{ runner.os == 'macOS' }}
    - uses: actions/setup-python@v7
      with:
        python-version: '3.13'
    - run: python -m pip install build meson meson-python ninja vapoursynth wheel

    - run: CC=clang-cl CXX=clang-cl CFLAGS="-march=x86-64-v3 -mtune=znver2 -Werror" CXXFLAGS="-march=x86-64-v3 -mtune=znver2 -Werror" LDFLAGS="-fuse-ld=lld" python -m build --no-isolation
      if: ${{ runner.os == 'Windows' && runner.arch == 'X64' }}
    - run: CC=clang CXX=clang++ CFLAGS="-march=x86-64-v3 -mtune=znver2 -Werror" CXXFLAGS="-march=x86-64-v3 -mtune=znver2 -Werror" LDFLAGS="-fuse-ld=lld --rtlib=compiler-rt -Wl,-O3" python -m build --no-isolation
      if: ${{ runner.os == 'Linux' && runner.arch == 'X64' }}
    - run: PATH="/opt/homebrew/opt/llvm/bin:$PATH" CC=clang CXX=clang++ CFLAGS="-I/opt/homebrew/opt/llvm/include -march=armv8.5-a+simd+crypto -mtune=apple-m3 -Werror" CXXFLAGS="-I/opt/homebrew/opt/llvm/include -march=armv8.5-a+simd+crypto -mtune=apple-m3 -Werror" LDFLAGS="-fuse-ld=lld --rtlib=compiler-rt -L/opt/homebrew/opt/llvm/lib" python -m build --no-isolation
      if: ${{ runner.os == 'macOS' && runner.arch == 'ARM64' }}
    - run: PATH="/opt/homebrew/opt/llvm/bin:$PATH" CC=clang CXX=clang++ CFLAGS="-I/opt/homebrew/opt/llvm/include -march=skylake -mtune=skylake -Werror" CXXFLAGS="-I/opt/homebrew/opt/llvm/include -march=skylake -mtune=skylake -Werror" LDFLAGS="-fuse-ld=lld --rtlib=compiler-rt -L/opt/homebrew/opt/llvm/lib" python -m build --no-isolation
      if: ${{ runner.os == 'macOS' && runner.arch == 'X64' }}
    - run: python -m wheel tags --remove --python-tag py3 --abi-tag none dist/*.whl

    - uses: actions/upload-artifact@v7
      with:
        name: '${{ runner.os }} ${{ runner.arch }}'
        path: dist/*

  release:
    needs: [build]
    if: ${{ github.event_name == 'release' }}
    environment:
      name: pypi
      url: https://pypi.org/p/vapoursynth-letterbox
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v8
      with:
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
